Updates logger library to v1.1.

diff --git a/libs/logger b/libs/logger
--- a/libs/logger
+++ b/libs/logger
@@ -1,6 +1,13 @@
 #! /usr/bin/env bash
 
-# VERSION=v1.0
+# VERSION=v1.1
+
+case "${BASH_VERSINFO[0]}.${BASH_VERSINFO[1]}" in
+    [1-3].* | 4.[1-3] )
+        >&2 echo "Least required version of bash is 4.4."
+        exit 1
+    ;;
+esac
 
 declare -A _LOGGER_LEVELS_MAP=( [A]=0 [T]=1 [D]=2 [I]=3 [N]=4 [W]=5 [E]=6 [C]=7 )
 
@@ -28,8 +35,17 @@ function logger::__message() {
     local message="${2}"
 
     local datetime="\D{%d.%m.%Y %H:%M:%S}"
+    local line="[${datetime@P}] ${level}: ${message}"
 
-    >&2 echo "[${datetime@P}] ${level}: ${message}"
+    if [[ -z "${_LOGGER_FILEPATH+_}" ]]; then
+        >&2 echo "${line}"
+    else
+        echo "${line}" >> "${_LOGGER_FILEPATH}" || {
+            # if saving log message to file fails, print it to STDERR
+            >&2 echo "[${datetime@P}] C: Cannot write to log file '${_LOGGER_FILEPATH}' anymore."
+            >&2 echo "${line}"
+        }
+    fi
 }
 
 function logger::__terminate() {
@@ -41,9 +57,9 @@ function logger::__terminate() {
     exit 1
 }
 
-function logger::__is_level_set() {
+function logger::__is_global_level_set() {
     if [[ -z "${_LOGGER_LEVEL+_}" ]]; then
-        logger::__terminate "Level is not set."
+        logger::__terminate "Global level is not set."
     fi
 }
 
@@ -55,19 +71,51 @@ function logger::__validate_level() {
     fi
 }
 
+function logger::__prepare_log() {
+    local log_filepath="${1}"
+
+    if [[ -d "${log_filepath}" ]]; then
+        logger::__terminate "'${log_filepath}' is a directory."
+    elif [[ -e "${log_filepath}" ]] && ! [[ -w "${log_filepath}" ]]; then
+        logger::__terminate "Log file '${log_filepath}' is not writable."
+    fi
+
+    if [[ -w "${log_filepath}" ]]; then
+        return
+    fi
+
+    local log_dirpath="$(dirname "${log_filepath}")"
+
+    if [[ ! -d "${log_dirpath}" ]]; then
+        logger::log "I" "Creating log directory '${log_dirpath}'."
+        mkdir -p "${log_dirpath}" || logger::__terminate "Cannot create log directory '${log_dirpath}'."
+    fi
+
+    touch "${log_filepath}" || logger::__terminate "Cannot create log file '${log_filepath}'."
+}
+
 function logger::init() {
     local level="${1}"
+    local log_filepath=""
 
     logger::__validate_level "${level}"
 
     _LOGGER_LEVEL="${level}"
+
+    if [[ ${#} -eq 2 ]]; then
+        log_filepath="${2}"
+
+        logger::__prepare_log "${log_filepath}"
+
+        _LOGGER_FILEPATH="${log_filepath}"
+    fi
 }
 
 function logger::log() {
     local level="${1}"
     local message="${@:2}"
 
-    logger::__is_level_set
+    logger::__is_global_level_set
     logger::__validate_level "${level}"
 
     # level A is allowed only for
