Prevents concurent copying of transport files to multiple system from the same transport domain (fixes #24, fixes #34).

diff --git a/libs/saptransport b/libs/saptransport
--- a/libs/saptransport
+++ b/libs/saptransport
@@ -13,6 +13,7 @@ SAPTRANSPORT_STATUS_RUNNING="RUNNING"
 SAPTRANSPORT_STATUS_FAILED="FAILED"
 SAPTRANSPORT_STATUS_FINISHED="FINISHED"
 SAPTRANSPORT_STATUS_SKIPPED="SKIPPED"
+SAPTRANSPORT_STATUS_WAITING="WAITING"
 
 SAPTRANSPORT_STATUS_FILENAME_PART="saptransport_status"
 SAPTRANSPORT_ABORT_FILENAME="saptransport_abort"
@@ -125,6 +126,11 @@ function saptransport::__run_action_on_system() {
             local ssh_port="22"
 
             local domain_controller_source="${SAPTRANSPORT_TRANSPORT_DOMAINS_MAP[${sid_source}]}"
+            local selected_system="$(saptransport::__get_system_from_requested_transport_domain "${domain_controller}" "${IP_SYSTEM_LIST[@]}")" || { \
+                saptransport::record_status "${SAPTRANSPORT_STATUS_FAILED}" "${transport}" "${system}" "${action}"
+
+                tpcp::utils::terminate "Cannot find system from requested transport domain ${domain_controller}."
+            }
 
             # copying transport files within a transport domain
             if [[ "${domain_controller_source}" == "${domain_controller}" ]]; then
@@ -133,7 +139,53 @@ function saptransport::__run_action_on_system() {
                 saptransport::record_status "${SAPTRANSPORT_STATUS_SKIPPED}" "${transport}" "${system}" "${action}"
 
                 return 0
+
+            # copying transport files across transport domains but this is not selected system
+            elif [[ "${system}" != "${selected_system}" ]]; then
+                logger::log "${TPCP_CURRENT_LABEL}" "N" "Transport files will be copied only to selected system ${selected_system} (source=DOMAIN_${domain_controller_source}, target=DOMAIN_${domain_controller})."
+
+                logger::log "${TPCP_CURRENT_LABEL}" "N" "Waiting for transport copy to finish on selected system ${selected_system}."
+
+                saptransport::record_status "${SAPTRANSPORT_STATUS_WAITING}" "${transport}" "${system}" "${action}"
+
+                while : ; do
+                    sleep 1
+
+                    local status="$(saptransport::read_status "${transport}" "${selected_system}" "${action}")"
+
+                    case "${status}" in
+                        "${SAPTRANSPORT_STATUS_FINISHED}" )
+                            logger::log "${TPCP_CURRENT_LABEL}" "N" "Waiting for transport copy to finish on selected system ${selected_system}."
+
+                            break
+                        ;;
+
+                        "${SAPTRANSPORT_STATUS_FAILED}" )
+                            logger::log "${TPCP_CURRENT_LABEL}" "E" "Copying transport files to selected system ${selected_system} failed."
+
+                            saptransport::record_status "${SAPTRANSPORT_STATUS_FAILED}" "${transport}" "${system}" "${action}"
+
+                            return 1
+                        ;;
+
+                        "${SAPTRANSPORT_STATUS_SKIPPED}" | "${SAPTRANSPORT_STATUS_WAITING}" )
+                            logger::log "${TPCP_CURRENT_LABEL}" "E" "Copying action on selected system ${selected_system} cannot be in this state ${status}."
+
+                            saptransport::record_status "${SAPTRANSPORT_STATUS_FAILED}" "${transport}" "${system}" "${action}"
+
+                            return 1
+                        ;;
+                    esac
+                done
+
+                logger::log "${TPCP_CURRENT_LABEL}" "N" "Transport files were successfully copied to selected system ${selected_system}."
+
+                saptransport::record_status "${SAPTRANSPORT_STATUS_SKIPPED}" "${transport}" "${system}" "${action}"
+
+                return 0
             fi
+
+            logger::log "${TPCP_CURRENT_LABEL}" "I" "Copying transport files since this is selected system."
 
             ssh_commands+=("scp -p -o ConnectTimeout=5 -o BatchMode=yes -P ${ssh_target_port} /usr/sap/trans/cofiles/K${transport_label}.${sid_source} ${ssh_target_user}@${ssh_target_host}:/usr/sap/trans/cofiles/")
             ssh_commands+=("scp -p -o ConnectTimeout=5 -o BatchMode=yes -P ${ssh_target_port} /usr/sap/trans/data/R${transport_label}.${sid_source} ${ssh_target_user}@${ssh_target_host}:/usr/sap/trans/data/")
@@ -280,7 +332,7 @@ function saptransport::is_all_done() {
         case "${status}" in
             # FIX: There was a race condition due to changing status is not an atomic operation.
             #      The status of subsequent action is changed first to fix thix.
-            "${SAPTRANSPORT_STATUS_RUNNING}" )
+            "${SAPTRANSPORT_STATUS_RUNNING}" | "${SAPTRANSPORT_STATUS_WAITING}" )
                 logger::log "${TPCP_CURRENT_LABEL}" "D" "Not yet done, status '${status}' is stored in '${status_filepath}'."
 
                 return 1
@@ -452,6 +504,55 @@ function saptransport::__hostname_exists() {
     if ! [[ ${SAPTRANSPORT_HOSTNAMES_MAP[${sid}]+_} ]]; then
         return 1
     fi
+}
+
+function saptransport::__get_system_from_requested_transport_domain() {
+    local domain_controller="${1}"
+    local system_list=("${@:2}") # assert: order of passed array stays always the same
+
+    logger::log "${TPCP_CURRENT_LABEL}" "T" "Running ${FUNCNAME}():"
+    logger::log "${TPCP_CURRENT_LABEL}" "T" "   domain_controller=${domain_controller}"
+    logger::log "${TPCP_CURRENT_LABEL}" "T" "   system_list=${system_list[*]}"
+
+    logger::log "${TPCP_CURRENT_LABEL}" "D" "Searching for system from requested transport domain ${domain_controller} (system_list=${system_list[*]})."
+
+    # doing it this way so it is cross-platform (egrep -o works only with GNU egrep)
+    local selected_system="$(echo -n "${system_list[@]}" | tr ' ' "\n" | egrep "^${domain_controller}[0-9]{3}\$" | head -n 1)" \
+        || logger::log "${TPCP_CURRENT_LABEL}" "E" "Searching for domain controller system for requested transport domain ${domain_controller} in system list failed."
+
+    # prefer domain controller
+    if [[ "${selected_system}" != "" ]]; then
+        logger::log "${TPCP_CURRENT_LABEL}" "D" "Found domain controller system ${selected_system} for requested transport domain ${domain_controller}."
+
+        echo -n "${selected_system}"
+
+        return 0
+    fi
+
+    # choose any system from the same transport domain
+    logger::log "${TPCP_CURRENT_LABEL}" "D" "Domain controller system from requested transport domain ${domain_controller} not found."
+    logger::log "${TPCP_CURRENT_LABEL}" "D" "Searching for any system from requested transport domain ${domain_controller}."
+
+    local system
+
+    for system in ${system_list[@]}; do
+        local sid_discovered="$(saptransport::__get_sid "${system}")"
+        local domain_controller_discovered="${SAPTRANSPORT_TRANSPORT_DOMAINS_MAP[${sid_discovered}]}"
+
+        if [[ "${domain_controller}" == "${domain_controller_discovered}" ]]; then
+            logger::log "${TPCP_CURRENT_LABEL}" "D" "Found system ${system} from requested transport domain ${domain_controller}."
+
+            echo -n "${system}"
+
+            return 0
+        fi
+
+        logger::log "${TPCP_CURRENT_LABEL}" "D" "System ${system} is not from requested transport domain (requested=${domain_controller}, discovered=${domain_controller_discovered})."
+    done
+
+    logger::log "${TPCP_CURRENT_LABEL}" "E" "No system found for requested transport domain ${domain_controller}."
+
+    return 1
 }
 
 function saptransport::load_ini_file() {
